### PR TITLE
Shaojie

### PR DESCRIPTION
**Pull request by tayshaojie**
added slight edits to Fragment AddNewPatient.xml

### CODE REVIEW

**Comment by hari-allamraju** [comment]
I just pushed to master to remove .idea folder from the git tree and also updated few other files - can you pull those and update the pull request? that will reduce some of the conflicts

**Comment by hari-allamraju** [comment]
if you do a update from master in github desktop that should merge and clear the 3 conflicts listed here

**Comment by tayshaojie** [comment]
should be ok now - thanks!

**Comment by hari-allamraju** [comment]
Perfect - merging now

**Comment by hari-allamraju** [comment]
merge done - left the branch as is so that you can keep working on it
will merge my build tools changes tomorrow and update everyone to pull from master

**Pull request merged**
